eeg:
  reject: # high threshold in volts (e.g. 0.00004); blank (None) to keep all epochs
  interpolate: false
  ref_channel: ['Ch17']
clf_type: svm
process_individual_subjs: true
dss:
  use: true
  save_mat: true
  save_data: true
  use_n_channels: 4
pca:
  time_domain: true
  truncate_to_n_timepts:  # 20 is reasonable, leave unset (=None) to disable
n_jobs: 6  # 'cuda' is also an option
align_on_cv: true  # epoch t0 = stimulus onset (false) or cv transition (true)
brain_resp_dur: 0.2
features_file: consonant-features-transposed-sparse-jfh.tsv
subjects:
  IJ: 1
  IL: 2
  FA: 3
  IM: 4
  ID: 5
  CQ: 6
  IP: 7
  FV: 8
  IA: 9
  IV: 10
  IQ: 11
  IT: 12
# skip: ['IJ', 'IL', 'FA', 'IM', 'ID', 'CQ', 'IP', 'FV', 'IA', 'IV', 'IQ', 'IT']
skip: []
blink_channel:
  FV: Ch1
  IQ: Ch1
  IP: Ch1
  IT: Ch1
  IV: Ch1
  FA: Ch2  # Ch1 noisy
  IJ: Ch1
  IM: Ch1
  IL: Ch1
  IA: Ch1
  CQ: Ch1
  ID: Ch1


n_components_needed_for_blink_eradication:
  IJ: 4  # 5 gets rid of correlated DC shifts
  IL: 4
  FA: 4  # 5 gets rid of correlated DC shifts
  IM: 4  # 4 is pretty good, 5 not obv. better
  ID: 3
  CQ: 4  # 5 gets rid of correlated DC shifts
  IP: 4  # 4 is pretty good, 5 not obv. better
  FV: 5  # component 4 seems unnecessary
  IA: 5  # component 2 seems unnecessary
  IV: 5 or more  # not sure how many needed.. comp. 4's utility unclear
  IQ: 4  # component 3 seems unnecessary; 5 does not handle DC
  IT: 5  # 4 does a pretty good job
