eeg:
  reject:  # high threshold in volts; dict or blank (None) to keep all epochs
    eeg: 0.000075
  interpolate: false
  ref_channel: ['Ch17']

dss:
  use: true
  save_mat: true
  save_data: true
  n_components: 5

pca:
  time_domain: true
  truncate_to_n_timepts:  # 20 is reasonable, leave unset (=None) to disable

n_jobs: 6  # 'cuda' is hard-coded on some lines (for filtering, resampling)

align_on_cv: true  # epoch t0 = stimulus onset (false) or cv transition (true)

brain_resp_dur: 0.2

use_eer_in_plots: true

subjects:
  IJ: 1
  IL: 2
  FA: 3
  IM: 4
  ID: 5
  CQ: 6
  IP: 7
  FV: 8
  IA: 9
  IV: 10
  IQ: 11
  IT: 12

# skip: ['IJ', 'IL', 'FA', 'IM', 'ID', 'CQ', 'IP', 'FV', 'IA', 'IV', 'IQ', 'IT']
skip: ['IA']

subj_langs:
  IJ: ['eng', 'hin', 'hun']
  IL: ['eng', 'hin', 'swh']
  FA: ['eng', 'hin', 'nld']
  IM: ['eng', 'hun', 'swh']
  ID: ['eng', 'hun', 'nld']
  CQ: ['eng', 'nld', 'swh']
  IP: ['eng', 'hin', 'hun']
  FV: ['eng', 'hin', 'swh']
  IA: ['eng', 'hin', 'nld']
  IV: ['eng', 'hun', 'swh']
  IQ: ['eng', 'hun', 'nld']
  IT: ['eng', 'nld', 'swh']
  theory: ['eng', 'hin', 'hun', 'nld', 'swh']

blink_channel:
  FV: Ch1
  IQ: Ch1
  IP: Ch1
  IT: Ch1
  IV: Ch1
  FA: Ch2  # Ch1 noisy
  IJ: Ch1
  IM: Ch1
  IL: Ch1
  IA: Ch1
  CQ: Ch1
  ID: Ch1

bad_channels:
  IJ: ['Ch3', 'Ch7']  # 32
  IL: []
  FA: ['Ch7']  # 2, 8, 20
  IM: ['Ch3']  # 7, 22
  ID: ['Ch16', 'Ch12', 'Ch7']
  CQ: ['Ch3']
  IP: []  # 7, 11, 15, 3
  FV: ['Ch2', 'Ch7', 'Ch1']
  IA: ['Ch3']  # 22
  IV: ['Ch1', 'Ch16', 'Ch7']
  IQ: ['Ch7', 'Ch3']
  IT: ['Ch3']

# features
features: ['vocalic',
           'consonantal',
           'nasal',
           'flat',
           'continuant',
           'strident',
           'compact',
           'grave',
           'tense',
           'nasal_sparse',
           'flat_sparse',
           'continuant_sparse',
           'strident_sparse',
           'compact_sparse',
           'grave_sparse',
           'tense_sparse',
           'vocalic_spe',
           'consonantal_spe',
           'continuant_spe',
           'voiced',
           'coronal',
           'anterior',
           'high',
           'back',
           'low',
           'strident_spe',
           'nasal_spe_sparse',
           'continuant_spe_sparse',
           'voiced_spe_sparse',
           'strident_spe_sparse',
           'dorsal',
           'lateral',
           'anterior_sparse',
           'sonorant',
           'strident_phoible',
           'distributed',
           'delayedrelease']

feature_systems:
  jfh_dense: ['vocalic', 'consonantal', 'nasal', 'flat', 'continuant',
              'strident', 'compact', 'grave', 'tense']
  jfh_sparse: ['vocalic', 'consonantal', 'nasal_sparse', 'flat_sparse',
               'continuant_sparse', 'strident_sparse', 'compact_sparse',
               'grave_sparse', 'tense_sparse']
  spe_dense: ['vocalic_spe', 'consonantal_spe', 'nasal', 'continuant_spe',
              'voiced', 'coronal', 'anterior', 'high', 'back', 'low',
              'strident_spe']
  spe_sparse: ['vocalic_spe', 'consonantal_spe', 'nasal_spe_sparse', 
               'continuant_spe_sparse', 'voiced_spe_sparse', 'coronal',
               'anterior', 'high', 'back', 'low', 'strident_spe_sparse']
  phoible_sparse: ['vocalic', 'consonantal', 'nasal', 'flat', 'continuant_spe',
                   'voiced', 'coronal', 'dorsal', 'lateral', 'anterior_sparse',
                   'sonorant', 'distributed', 'delayedrelease',
                   'strident_phoible']

feature_mappings:
  jfh_dense:
    vocalic: vocalic
    consonantal: consonantal
    nasal: nasal
    flat: flat
    continuant: continuant
    strident: strident
    compact: compact
    grave: grave
    tense: tense
  jfh_sparse:
    vocalic: vocalic
    consonantal: consonantal
    nasal_sparse: nasal
    flat_sparse: flat
    continuant_sparse: continuant
    strident_sparse: strident
    compact_sparse: compact
    grave_sparse: grave
    tense_sparse: tense
  spe_dense:
    vocalic_spe: vocalic
    consonantal_spe: consonantal
    nasal: nasal
    continuant_spe: continuant
    voiced: voiced
    coronal: coronal
    anterior: anterior
    high: high
    back: back
    low: low
    strident_spe: strident
  spe_sparse:
    vocalic_spe: vocalic
    consonantal_spe: consonantal
    nasal_spe_sparse: nasal
    continuant_spe_sparse: continuant
    voiced_spe_sparse: voiced
    coronal: coronal
    anterior: anterior
    high: high
    back: back
    low: low
    strident_spe_sparse: strident
  phoible_sparse:
    vocalic: approximant
    consonantal: consonantal
    nasal: nasal
    flat: labial
    continuant_spe: continuant
    voiced: voiced
    coronal: coronal
    dorsal: dorsal
    lateral: lateral
    anterior_sparse: anterior
    sonorant: sonorant
    distributed: distributed
    delayedrelease: delayedrelease
    strident_phoible: strident

feature_fnames:
  jfh_dense: consonant-features-transposed-dense-jfh.tsv
  jfh_sparse: consonant-features-transposed-sparse-jfh.tsv
  spe_dense: consonant-features-transposed-dense-spe.tsv
  spe_sparse: consonant-features-transposed-sparse-spe.tsv
  phoible_sparse: consonant-features-transposed-sparse-phoible_ext.tsv

canonical_phone_order:
  eng: ['p', 'b', 't', 'd', 'k', 'ɡ', 'tʃ', 'dʒ', 'f', 'v', 'θ', 'ð', 's', 'z',
        'ʃ', 'ʒ', 'm', 'n', 'h', 'l', 'ɹ', 'j', 'w']
  hin: ['p', 'b', 'bʱ', 't̪ʰ', 't̪', 'd̪', 'd̪̤', 'ʈʰ', 'ʈ', 'ɖ', 'ɖ̤', 'k', 'kʰ',
        'ɡ', 'ɡ̤', 't̠ʃʰ', 't̠ʃ', 'd̠ʒ', 'd̠ʒ̤', 'f', 's', 'ʃ', 'ʂ', 'm', 'n', 'h',
        'l', 'r', 'j', 'ʋ']
  hun: ['pʰ', 'b', 't̪ʰ', 'd̪', 'cʰ', 'ɟ', 'kʰ', 'ɡ', 'tsʰ', 'dz', 't̠ʃʰ', 'd̠ʒ',
        'f', 'v', 's', 'z', 'ʃ', 'ʒ', 'm', 'n̪', 'ɲ', 'h', 'l̪', 'r̪', 'j']
  nld: ['p', 'b', 'tʰ', 'd', 'kʰ', 'f', 'v', 's', 'z', 'ʃ', 'x', 'ʀ', 'm', 'n',
        'h', 'l', 'j', 'ʋ']
  swh: ['pʰ', 'b', 'tʰ', 'ɗ', 'ɟ', 'kʰ', 't̠ʃʰ', 'f', 'v', 'θ', 'ð', 's', 'z',
        'ʃ', 'ɣ', 'm', 'n', 'ɲ', 'ŋ', 'mb', 'nd', 'ɲɟ', 'ŋɡ', 'ɱv', 'nz', 'h',
        'l', 'r', 'j', 'w']

# below are just notes, not read in by any scripts:

n_components_needed_for_blink_eradication:
  IJ: 4  # 5 gets rid of correlated DC shifts
  IL: 4
  FA: 4  # 5 gets rid of correlated DC shifts
  IM: 4  # 4 is pretty good, 5 not obv. better
  ID: 3
  CQ: 4  # 5 gets rid of correlated DC shifts
  IP: 4  # 4 is pretty good, 5 not obv. better
  FV: 5  # component 4 seems unnecessary
  IA: 5  # component 2 seems unnecessary
  IV: 5 or more  # not sure how many needed.. comp. 4's utility unclear
  IQ: 4  # component 3 seems unnecessary
  IT: 5  # 4 does a pretty good job

memory_per_classifier_thread: 255M
